apiVersion: v1
kind: Service
metadata:
  name: ad-service
spec:
  ports:
  - name: ad-service
    port: 9555
    protocol: TCP
    targetPort: 9555
  selector:
    app: ad-deploy
  type: ClusterIP
status:
  loadBalancer: {}
