stages:
  - build
  - test
  - deploy

variables:
  IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

# --- Stage 1: Build และ Push ขึ้น GitLab ---
build_job:
  stage: build
  image: docker:24.0.5
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  services:
    - name: docker:24.0.5-dind
  before_script:
    - echo "Logging in to $CI_REGISTRY..."
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - ls -la
    - docker build -t $IMAGE_NAME .
    - docker push $IMAGE_NAME

# --- Stage 2: Test (สแกนหาช่องโหว่ด้วย Trivy) ---
trivy_scan_job:       # 👈 2. สร้าง Job ใหม่
  stage: test         # 👈 3. อ้างอิง stage เป็น 'test'
  image:
    name: docker.io/aquasec/trivy:latest
    entrypoint: [""]
  variables:
    TRIVY_USERNAME: "$CI_REGISTRY_USER"
    TRIVY_PASSWORD: "$CI_REGISTRY_PASSWORD"
    TRIVY_AUTH_URL: "$CI_REGISTRY"
    TRIVY_CACHE_DIR: ".trivycache/"
  script:
    - echo "Scanning image $IMAGE_NAME with Trivy..."
    - trivy --version

    # 1. สแกนและออกรายงานเป็นไฟล์ JSON (เพิ่ม timeout 15 นาที และลดโหลดด้วย scanners vuln)
    - trivy image --timeout 15m --scanners vuln --exit-code 0 --format template --template "@/contrib/gitlab.tpl" --output gl-container-scanning-report.json "$IMAGE_NAME"
    
    # 2. พิมพ์ผลลัพธ์แบบสรุปให้ดูง่ายๆ ใน Log
    - trivy image --timeout 15m --scanners vuln --exit-code 0 --severity HIGH,CRITICAL "$IMAGE_NAME"
    
    # 3. (ทางเลือก) หยุด Pipeline ไม่ให้ Deploy ถ้าเจอช่องโหว่ระดับ CRITICAL
    - trivy image --timeout 15m --scanners vuln --exit-code 1 --severity CRITICAL "$IMAGE_NAME"

  cache:              # 👈 เก็บ Cache ฐานข้อมูลของ Trivy ไว้ใช้รอบหน้า
    paths:
      - .trivycache/      
  artifacts:          # 👈 ส่งไฟล์ Report ไปให้หน้าเว็บ GitLab แสดงผล
    when: always
    reports:
      container_scanning: gl-container-scanning-report.json

# --- Stage 3: Deploy to K8s ---
deploy_job:
  stage: deploy
  image: 
    name: bitnami/kubectl:latest
    entrypoint: [""]
  script:
    - if [ -z "$KUBE_CONFIG" ]; then echo "❌ KUBE_CONFIG is empty!"; exit 1; fi
    - echo "$KUBE_CONFIG" | base64 -d > kubeconfig.yaml
    - ls -la kubeconfig.yaml
    - find k8s/ -name "*.yaml" -exec sed -i "s|__IMAGE_NAME__|$IMAGE_NAME|g" {} +
    - kubectl --kubeconfig kubeconfig.yaml apply -f k8s/
    - kubectl --kubeconfig kubeconfig.yaml rollout status deployment/recommend-deploy

