apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ad-deploy
  name: ad-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ad-deploy
  strategy: {}
  template:
    metadata:
      labels:
        app: ad-deploy
    spec:
      serviceAccountName: adservice
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: server
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
        image: __IMAGE_NAME__
        ports:
        - containerPort: 9555
        env:
        - name: PORT
          value: "9555"
        resources:
          requests:
            cpu: 200m
            memory: 180Mi
          limits:
            cpu: 300m
            memory: 300Mi
        # 1. เพิ่ม Startup Probe (ยามหน้าประตูช่วงสตาร์ท)
        startupProbe:
          grpc:
            port: 9555
          initialDelaySeconds: 10
          failureThreshold: 30 # ให้โอกาสลอง 30 ครั้ง
          periodSeconds: 5     # 30 * 5 = 150 วินาที (ให้เวลาแอปสตาร์ทได้ถึง 2.5 นาที)
        readinessProbe:
          initialDelaySeconds: 40
          periodSeconds: 15
          grpc:
            port: 9555
          timeoutSeconds: 5
        livenessProbe:
          initialDelaySeconds: 40
          periodSeconds: 15
          grpc:
            port: 9555
          timeoutSeconds: 5
      imagePullSecrets:
      - name: gitlab-registry-key
status: {}
