apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: payment-deploy
  name: payment-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-deploy
  strategy: {}
  template:
    metadata:
      labels:
        app: payment-deploy
    spec:
      serviceAccountName: paymentservice
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: server
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
        image: __IMAGE_NAME__
        ports:
        - containerPort: 50051
        env:
        - name: PORT
          value: "50051"
        - name: DISABLE_PROFILER
          value: "1"
        readinessProbe:
          grpc:
            port: 50051
        livenessProbe:
          grpc:
            port: 50051
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
      imagePullSecrets:
      - name: gitlab-registry-key
status: {}
